export const LOCATION = [
  "강남",
  "송파",
  "서초",
  "강동",
  "동작",
  "관악",
  "영등포",
  "강서",
  "양천",
  "구로",
  "금천",
  "종로",
  "중",
  "동대문",
  "중랑",
  "마포",
  "용산",
  "성동",
  "광진",
  "은평",
  "서대문",
  "성북",
  "강북",
  "도봉",
  "노원",
];

export const TOP_MENU = [
  {
    title: "재즈바",
    url: "/location",
  },
  {
    title: "공연",
    url: "/live",
  },
  {
    title: "달력",
    url: "/calendar",
  },
];

export const JAZZ_BAR = [
  {
    id: "jazz_bar_1",
    title: "부기우기",
    description: "용산구 작지만 알찬 부기우기, 가성비 있다",
    address1: "서울 용산구 회나무로 21 2층",
    contact_number: "010-2396-3050",
    img_url: "/images/location/boogie_woogie.jpg",
    favorite: false,
  },
  {
    id: "jazz_bar_2",
    title: "재즈라운지",
    description: "라운지와 재즈 그 사이 어딘가",
    // address1: "서울 광진구 능동로19길 7-6 재즈라운지 1층",
    address1: "서울 광진구 능동로19길 재즈라운지",
    contact_number: "0507-1421-1998",
    img_url: "/images/location/jazz_lounge.jpg",
    favorite: false,
  },
  {
    id: "jazz_bar_3",
    title: "연남5701",
    description: "연남동 지하에 위치한 재즈바",
    address1: "서울 마포구 동교로23길 64 지하",
    contact_number: "0507-1344-8161",
    img_url: "/images/location/yeonam5701.jpg",
    favorite: false,
  },
  {
    id: "jazz_bar_4",
    title: "플랫나인",
    description: "역시 재즈 트럼팻은 비플랫",
    address1: "서울 서초구 강남대로65길 10 5층",
    contact_number: "0507-1389-9630",
    img_url: "/images/location/flatnine.jpg",
    favorite: false,
  },
  {
    id: "jazz_bar_5",
    title: "부기우기",
    description: "용산구 작지만 알찬 부기우기, 가성비 있다",
    address1: "서울 용산구 회나무로 21 2층",
    contact_number: "010-2396-3050",
    img_url: "/images/location/boogie_woogie.jpg",
    favorite: false,
  },
  {
    id: "jazz_bar_6",
    title: "재즈라운지",
    description: "라운지와 재즈 그 사이 어딘가",
    // address1: "서울 광진구 능동로19길 7-6 재즈라운지 1층",
    address1: "서울 광진구 능동로19길 재즈라운지",
    contact_number: "0507-1421-1998",
    img_url: "/images/location/jazz_lounge.jpg",
    favorite: false,
  },
  {
    id: "jazz_bar_7",
    title: "연남5701",
    description: "연남동 지하에 위치한 재즈바",
    address1: "서울 마포구 동교로23길 64 지하",
    contact_number: "0507-1344-8161",
    img_url: "/images/location/yeonam5701.jpg",
    favorite: false,
  },
  {
    id: "jazz_bar_8",
    title: "플랫나인",
    description: "역시 재즈 트럼팻은 비플랫",
    address1: "서울 서초구 강남대로65길 10 5층",
    contact_number: "0507-1389-9630",
    img_url: "/images/location/flatnine.jpg",
    favorite: false,
  },
];
