export type LocationType = {
  location_id: string;
  name: string;
  image_id: string;
  image_url: string;
  caption: string;
  address: string;
  direction: string;
  city: string;
  gu: string;
  zipcode: string;
  phone_number: string;
  website: string;
  instagram: string;
  catch_table: string;
  naver_url: string;
  opening_hour: string;
  opening_hour0: string;
  opening_hour1: string;
  opening_hour2: string;
  opening_hour3: string;
  opening_hour4: string;
  opening_hour5: string;
  opening_hour6: string;
  created_at: Date;
  updated_at: Date;
};
